/*
VRChat API Documentation


API version: 1.10.1
Contact: me@ariesclark.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vrchatapi

import (
	"encoding/json"
)

// APIConfigDownloadURLList Download links for various development assets.
type APIConfigDownloadURLList struct {
	// Download link for legacy SDK2
	// Deprecated
	Sdk2 string `json:"sdk2"`
	// Download link for SDK3 for Avatars
	Sdk3Avatars string `json:"sdk3-avatars"`
	// Download link for SDK3 for Worlds
	Sdk3Worlds string `json:"sdk3-worlds"`
}

// NewAPIConfigDownloadURLList instantiates a new APIConfigDownloadURLList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIConfigDownloadURLList(sdk2 string, sdk3Avatars string, sdk3Worlds string) *APIConfigDownloadURLList {
	this := APIConfigDownloadURLList{}
	this.Sdk2 = sdk2
	this.Sdk3Avatars = sdk3Avatars
	this.Sdk3Worlds = sdk3Worlds
	return &this
}

// NewAPIConfigDownloadURLListWithDefaults instantiates a new APIConfigDownloadURLList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIConfigDownloadURLListWithDefaults() *APIConfigDownloadURLList {
	this := APIConfigDownloadURLList{}
	return &this
}

// GetSdk2 returns the Sdk2 field value
// Deprecated
func (o *APIConfigDownloadURLList) GetSdk2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sdk2
}

// GetSdk2Ok returns a tuple with the Sdk2 field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *APIConfigDownloadURLList) GetSdk2Ok() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Sdk2, true
}

// SetSdk2 sets field value
// Deprecated
func (o *APIConfigDownloadURLList) SetSdk2(v string) {
	o.Sdk2 = v
}

// GetSdk3Avatars returns the Sdk3Avatars field value
func (o *APIConfigDownloadURLList) GetSdk3Avatars() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sdk3Avatars
}

// GetSdk3AvatarsOk returns a tuple with the Sdk3Avatars field value
// and a boolean to check if the value has been set.
func (o *APIConfigDownloadURLList) GetSdk3AvatarsOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Sdk3Avatars, true
}

// SetSdk3Avatars sets field value
func (o *APIConfigDownloadURLList) SetSdk3Avatars(v string) {
	o.Sdk3Avatars = v
}

// GetSdk3Worlds returns the Sdk3Worlds field value
func (o *APIConfigDownloadURLList) GetSdk3Worlds() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sdk3Worlds
}

// GetSdk3WorldsOk returns a tuple with the Sdk3Worlds field value
// and a boolean to check if the value has been set.
func (o *APIConfigDownloadURLList) GetSdk3WorldsOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Sdk3Worlds, true
}

// SetSdk3Worlds sets field value
func (o *APIConfigDownloadURLList) SetSdk3Worlds(v string) {
	o.Sdk3Worlds = v
}

func (o APIConfigDownloadURLList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sdk2"] = o.Sdk2
	}
	if true {
		toSerialize["sdk3-avatars"] = o.Sdk3Avatars
	}
	if true {
		toSerialize["sdk3-worlds"] = o.Sdk3Worlds
	}
	return json.Marshal(toSerialize)
}

type NullableAPIConfigDownloadURLList struct {
	value *APIConfigDownloadURLList
	isSet bool
}

func (v NullableAPIConfigDownloadURLList) Get() *APIConfigDownloadURLList {
	return v.value
}

func (v *NullableAPIConfigDownloadURLList) Set(val *APIConfigDownloadURLList) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIConfigDownloadURLList) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIConfigDownloadURLList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIConfigDownloadURLList(val *APIConfigDownloadURLList) *NullableAPIConfigDownloadURLList {
	return &NullableAPIConfigDownloadURLList{value: val, isSet: true}
}

func (v NullableAPIConfigDownloadURLList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIConfigDownloadURLList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


