/*
VRChat API Documentation


API version: 1.10.1
Contact: me@ariesclark.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vrchatapi

import (
	"encoding/json"
)

// CreateGroupRoleRequest struct for CreateGroupRoleRequest
type CreateGroupRoleRequest struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IsSelfAssignable *bool `json:"isSelfAssignable,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

// NewCreateGroupRoleRequest instantiates a new CreateGroupRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGroupRoleRequest() *CreateGroupRoleRequest {
	this := CreateGroupRoleRequest{}
	var isSelfAssignable bool = false
	this.IsSelfAssignable = &isSelfAssignable
	return &this
}

// NewCreateGroupRoleRequestWithDefaults instantiates a new CreateGroupRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGroupRoleRequestWithDefaults() *CreateGroupRoleRequest {
	this := CreateGroupRoleRequest{}
	var isSelfAssignable bool = false
	this.IsSelfAssignable = &isSelfAssignable
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateGroupRoleRequest) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGroupRoleRequest) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateGroupRoleRequest) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateGroupRoleRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateGroupRoleRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGroupRoleRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateGroupRoleRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateGroupRoleRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateGroupRoleRequest) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGroupRoleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateGroupRoleRequest) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateGroupRoleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIsSelfAssignable returns the IsSelfAssignable field value if set, zero value otherwise.
func (o *CreateGroupRoleRequest) GetIsSelfAssignable() bool {
	if o == nil || isNil(o.IsSelfAssignable) {
		var ret bool
		return ret
	}
	return *o.IsSelfAssignable
}

// GetIsSelfAssignableOk returns a tuple with the IsSelfAssignable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGroupRoleRequest) GetIsSelfAssignableOk() (*bool, bool) {
	if o == nil || isNil(o.IsSelfAssignable) {
    return nil, false
	}
	return o.IsSelfAssignable, true
}

// HasIsSelfAssignable returns a boolean if a field has been set.
func (o *CreateGroupRoleRequest) HasIsSelfAssignable() bool {
	if o != nil && !isNil(o.IsSelfAssignable) {
		return true
	}

	return false
}

// SetIsSelfAssignable gets a reference to the given bool and assigns it to the IsSelfAssignable field.
func (o *CreateGroupRoleRequest) SetIsSelfAssignable(v bool) {
	o.IsSelfAssignable = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *CreateGroupRoleRequest) GetPermissions() []string {
	if o == nil || isNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGroupRoleRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil || isNil(o.Permissions) {
    return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *CreateGroupRoleRequest) HasPermissions() bool {
	if o != nil && !isNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *CreateGroupRoleRequest) SetPermissions(v []string) {
	o.Permissions = v
}

func (o CreateGroupRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.IsSelfAssignable) {
		toSerialize["isSelfAssignable"] = o.IsSelfAssignable
	}
	if !isNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return json.Marshal(toSerialize)
}

type NullableCreateGroupRoleRequest struct {
	value *CreateGroupRoleRequest
	isSet bool
}

func (v NullableCreateGroupRoleRequest) Get() *CreateGroupRoleRequest {
	return v.value
}

func (v *NullableCreateGroupRoleRequest) Set(val *CreateGroupRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGroupRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGroupRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGroupRoleRequest(val *CreateGroupRoleRequest) *NullableCreateGroupRoleRequest {
	return &NullableCreateGroupRoleRequest{value: val, isSet: true}
}

func (v NullableCreateGroupRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGroupRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


