/*
VRChat API Documentation


API version: 1.10.1
Contact: me@ariesclark.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vrchatapi

import (
	"encoding/json"
)

// CreateFileVersionRequest struct for CreateFileVersionRequest
type CreateFileVersionRequest struct {
	SignatureMd5 string `json:"signatureMd5"`
	SignatureSizeInBytes float32 `json:"signatureSizeInBytes"`
	FileMd5 *string `json:"fileMd5,omitempty"`
	FileSizeInBytes *float32 `json:"fileSizeInBytes,omitempty"`
}

// NewCreateFileVersionRequest instantiates a new CreateFileVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFileVersionRequest(signatureMd5 string, signatureSizeInBytes float32) *CreateFileVersionRequest {
	this := CreateFileVersionRequest{}
	this.SignatureMd5 = signatureMd5
	this.SignatureSizeInBytes = signatureSizeInBytes
	return &this
}

// NewCreateFileVersionRequestWithDefaults instantiates a new CreateFileVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFileVersionRequestWithDefaults() *CreateFileVersionRequest {
	this := CreateFileVersionRequest{}
	return &this
}

// GetSignatureMd5 returns the SignatureMd5 field value
func (o *CreateFileVersionRequest) GetSignatureMd5() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignatureMd5
}

// GetSignatureMd5Ok returns a tuple with the SignatureMd5 field value
// and a boolean to check if the value has been set.
func (o *CreateFileVersionRequest) GetSignatureMd5Ok() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SignatureMd5, true
}

// SetSignatureMd5 sets field value
func (o *CreateFileVersionRequest) SetSignatureMd5(v string) {
	o.SignatureMd5 = v
}

// GetSignatureSizeInBytes returns the SignatureSizeInBytes field value
func (o *CreateFileVersionRequest) GetSignatureSizeInBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SignatureSizeInBytes
}

// GetSignatureSizeInBytesOk returns a tuple with the SignatureSizeInBytes field value
// and a boolean to check if the value has been set.
func (o *CreateFileVersionRequest) GetSignatureSizeInBytesOk() (*float32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SignatureSizeInBytes, true
}

// SetSignatureSizeInBytes sets field value
func (o *CreateFileVersionRequest) SetSignatureSizeInBytes(v float32) {
	o.SignatureSizeInBytes = v
}

// GetFileMd5 returns the FileMd5 field value if set, zero value otherwise.
func (o *CreateFileVersionRequest) GetFileMd5() string {
	if o == nil || isNil(o.FileMd5) {
		var ret string
		return ret
	}
	return *o.FileMd5
}

// GetFileMd5Ok returns a tuple with the FileMd5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFileVersionRequest) GetFileMd5Ok() (*string, bool) {
	if o == nil || isNil(o.FileMd5) {
    return nil, false
	}
	return o.FileMd5, true
}

// HasFileMd5 returns a boolean if a field has been set.
func (o *CreateFileVersionRequest) HasFileMd5() bool {
	if o != nil && !isNil(o.FileMd5) {
		return true
	}

	return false
}

// SetFileMd5 gets a reference to the given string and assigns it to the FileMd5 field.
func (o *CreateFileVersionRequest) SetFileMd5(v string) {
	o.FileMd5 = &v
}

// GetFileSizeInBytes returns the FileSizeInBytes field value if set, zero value otherwise.
func (o *CreateFileVersionRequest) GetFileSizeInBytes() float32 {
	if o == nil || isNil(o.FileSizeInBytes) {
		var ret float32
		return ret
	}
	return *o.FileSizeInBytes
}

// GetFileSizeInBytesOk returns a tuple with the FileSizeInBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFileVersionRequest) GetFileSizeInBytesOk() (*float32, bool) {
	if o == nil || isNil(o.FileSizeInBytes) {
    return nil, false
	}
	return o.FileSizeInBytes, true
}

// HasFileSizeInBytes returns a boolean if a field has been set.
func (o *CreateFileVersionRequest) HasFileSizeInBytes() bool {
	if o != nil && !isNil(o.FileSizeInBytes) {
		return true
	}

	return false
}

// SetFileSizeInBytes gets a reference to the given float32 and assigns it to the FileSizeInBytes field.
func (o *CreateFileVersionRequest) SetFileSizeInBytes(v float32) {
	o.FileSizeInBytes = &v
}

func (o CreateFileVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["signatureMd5"] = o.SignatureMd5
	}
	if true {
		toSerialize["signatureSizeInBytes"] = o.SignatureSizeInBytes
	}
	if !isNil(o.FileMd5) {
		toSerialize["fileMd5"] = o.FileMd5
	}
	if !isNil(o.FileSizeInBytes) {
		toSerialize["fileSizeInBytes"] = o.FileSizeInBytes
	}
	return json.Marshal(toSerialize)
}

type NullableCreateFileVersionRequest struct {
	value *CreateFileVersionRequest
	isSet bool
}

func (v NullableCreateFileVersionRequest) Get() *CreateFileVersionRequest {
	return v.value
}

func (v *NullableCreateFileVersionRequest) Set(val *CreateFileVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFileVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFileVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFileVersionRequest(val *CreateFileVersionRequest) *NullableCreateFileVersionRequest {
	return &NullableCreateFileVersionRequest{value: val, isSet: true}
}

func (v NullableCreateFileVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFileVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


